---
  title: "Analyze cell patterning data"
  output:
  html_document:
  df_print: paged
---
Iryna Hartsock


```{r global_options, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE)
# could also use warning=FALSE, message=FALSE
```
```{r setup}
knitr::opts_knit$set(root.dir="/Users/Iryna/Github/cell-patterning-project")
```
```{r libraries, message=FALSE}
library(tictoc)
#library(tdatools)
library(ggplot2)
library(ggpubr)
library(viridisLite)
library(viridis)
#library(rgl) #for plot3d
source("./source/intro_tda.R")
```


```{r GATA6 vs HA } 
vectorized_PLs <- cbind(vec_red[, (PL_length_red*0+1):(PL_length_red*30)])
#vectorized_PLs <- vec_red_1[, (PL_length_red*0+1):(PL_length_red*30)]


vec <- rbind(vectorized_PLs[(3*15*npatches+1):(4*15*npatches),], vectorized_PLs[(3*15*npatches+60*npatches+1):(60*npatches+4*15*npatches),])

#vectorized_PLs <- vectorized_PLs[1:(2*npatches),]
vec <- vec[, colSums(abs(vec)) != 0]

data_labels <- c(rep(1,15*npatches), rep(-1,15*npatches))
#data_labels <- c(rep("red",15*npatches), rep("blue",15*npatches))
pca <- prcomp(vec, scale=TRUE, rank=10)
#pca <- prcomp(rbind(counts[[1]][[2]],counts[[2]][[2]]), rank=10)
pca_df <- as.data.frame(pca$x)
label_1 <- matrix("Gata6", nrow=15*npatches, ncol=1)
label_2 <- matrix("HA", nrow=15*npatches, ncol=1)
markers <- rbind(label_1, label_2)
other_labels <- c(1:(15*npatches), (1+60*npatches):(15*npatches+60*npatches))
#other_labels <- c(1:(2*npatches))
p <- rep(c(1:9),15)
pca_with_labels <- data.frame(pca_df, other_labels = c(1:(15*npatches), (1+60*npatches):(15*npatches+60*npatches)))

colnames(pca_with_labels)[2] <- "Label"
colnames(pca_with_labels)[1] <- "number"
pca_with_labels_df <- as.data.frame(pca_with_labels)
ggplot(pca_df, aes(x=PC1, y=PC2, col=markers))+geom_point(size=1)+xlim(c(min(unlist(pca_df)),max(unlist(pca_df))))+ylim(c(min(unlist(pca_df)),max(unlist(pca_df))))+theme(aspect.ratio = 1)
ggplot(pca_df, aes(x=PC1, y=PC3, col=markers))+geom_point(size=1)+theme(aspect.ratio = 1)
ggplot(pca_df, aes(x=PC2, y=PC3, col=markers))+geom_point(size=1)+theme(aspect.ratio = 1)
#ggplot(data=pca_with_labels, aes(x=PC1, y=PC2, label=other_labels, col=p))+scale_color_viridis(option="D")+geom_point(size=1)+geom_text(data=subset(pca_with_labels, other_labels %in% c(1:9)))
#ggplot(data=pca_with_labels, aes(x=PC1, y=PC2, col=labels))+scale_color_viridis(option="D")+geom_point(size=1)#+geom_text(data=subset(pca_with_labels, other_labels %in% c(1:9)))
plot3d(pca_df, col=c(rep("red",15*npatches), rep("blue",15*npatches)))
```


```{r PCA-different-cell-types}
vectorized_PLs <- rbind(vec_red_1[, (PL_length_red*3+1):(PL_length_red*30)], vec_gr_1[,(PL_length_gr*3+1):(PL_length_gr*30)], vec_pos_1[,(PL_length_pos*3+1):(PL_length_pos*30)], vec_neg_1[,(PL_length_neg*3+1):(PL_length_neg*30)] )
cells <- c("deeppink",  "purple", "orange", "white")

m <- max(PL_length_red,PL_length_gr, PL_length_pos, PL_length_neg)
data_labels <- c(rep(1,15*9), rep(2,15*9), rep(3,15*9), rep(4,15*9))
pca <- prcomp(rbind(vec_red_1[(15*3*9+1):(15*4*9), (m*0+1):(m*30)],vec_gr_1[(15*3*9+1):(15*4*9), (m*0+1):(m*30)], vec_pos_1[(15*3*9+1):(15*4*9), (m*0+1):(m*30)], vec_neg_1[(15*3*9+1):(15*4*9), (m*0+1):(m*30)]))
pca_df <- as.data.frame(pca$x)
label_1 <- matrix("differentiated", nrow=nsamples*9, ncol=1)
label_2 <- matrix("pluripotent", nrow=nsamples*9, ncol=1)
label_3 <- matrix("transition", nrow=nsamples*9, ncol=1)
label_4 <- matrix("not pluripotent", nrow=nsamples*9, ncol=1)
labels <- rbind(label_1, label_2, label_3, label_4)
#other_labels <- c(46:60,106:120)
pca_with_labels <- cbind(labels, pca$x)
colnames(pca_with_labels)[1] <- "Label"
pca_with_labels_df <- as.data.frame(pca_with_labels)

ggplot(pca_df, aes(x=PC1, y=PC2, col=labels))+geom_point(size=1.4)+xlim(c(min(unlist(pca_df)),max(unlist(pca_df))))+ylim(c(min(unlist(pca_df)),max(unlist(pca_df))))+theme_dark()+theme(aspect.ratio = 1, panel.grid.minor.x=element_line(color="grey", size=0.1), panel.grid.minor.y=element_line(color="grey", size=0.1), panel.grid.major.x = element_line(color="grey", size=0.3), panel.grid.major.y = element_line(color="grey", size=0.3))+scale_color_manual(values=cells)

ggplot(pca_df, aes(x=PC1, y=PC3, col=labels))+geom_point(size=1.2)+theme_dark()+theme(aspect.ratio = 1, panel.grid.minor.x=element_line(color="grey", size=0.1), panel.grid.minor.y=element_line(color="grey", size=0.1), panel.grid.major.x = element_line(color="grey", size=0.3), panel.grid.major.y = element_line(color="grey", size=0.3))+scale_color_manual(values=cells)

ggplot(pca_df, aes(x=PC2, y=PC3, col=labels))+geom_point(size=1.2)+theme_dark()+theme(aspect.ratio = 1, panel.grid.minor.x=element_line(color="grey", size=0.1), panel.grid.minor.y=element_line(color="grey", size=0.1), panel.grid.major.x = element_line(color="grey", size=0.3), panel.grid.major.y = element_line(color="grey", size=0.3))+scale_color_manual(values=cells)
#ggplot(pca_df, aes(x=PC1, y=PC2, col=pca_with_labels_df$Label))+geom_point(size=1)+geom_text(label=other_labels, hjust=1, vjust=1)+geom_count()

```

```{r concentrations}
data_labels <- c(rep(1,15), rep(2,15), rep(3,15), rep(4,15), rep(1,15), rep(2,15), rep(3,15), rep(4,15))
pca <- prcomp(vectorized_avgPLs_im[1:120,])
pchs <- c (rep("GATA6", 60), rep("HA", 60))
pca_df <- as.data.frame(pca$x)
label_1 <- matrix("0 ng/ml", nrow=nimages, ncol=1)
label_2 <- matrix("5 ng/ml", nrow=nimages, ncol=1)
label_3 <- matrix("15 ng/ml", nrow=nimages, ncol=1)
label_4 <- matrix("25 ng/ml", nrow=nimages, ncol=1)
Dox_concentration <- rbind(label_1, label_2, label_3, label_4, label_1, label_2, label_3, label_4)
other_labels <- c(1:120)
pca_with_labels <- cbind(Dox_concentration, pchs, pca$x)
colnames(pca_with_labels)[1] <- "Label"
colnames(pca_with_labels)[2] <- "Symbol"
pca_with_labels_df <- as.data.frame(pca_with_labels)

ggplot(pca_df, aes(x=PC1, y=PC2, colour = Dox_concentration, shape = factor(pchs)))+geom_point(size=1.3)+theme(aspect.ratio = 1)+labs(
         colour = "Dox concentration",
         shape = "Group"
        )+scale_color_discrete(breaks=c("0 ng/ml","5 ng/ml","15 ng/ml", "25 ng/ml"))
ggplot(pca_df, aes(x=PC2, y=PC3, col=Dox_concentration))+geom_point(size=1.3)+theme(aspect.ratio = 1)
ggplot(pca_df, aes(x=PC1, y=PC3, col=Dox_concentration))+geom_point(size=1.3)+theme(aspect.ratio = 1)
```
```{r G vs HA 25 concentration}
data_labels <- c(rep(1,15), rep(2,15))
pca <- prcomp(rbind(vec_red[46:60,], vec_red[106:120,]))
pca_df <- as.data.frame(pca$x)
label_1 <- matrix("GATA6", nrow=nimages, ncol=1)
label_2 <- matrix("HA", nrow=nimages, ncol=1)
Labels <- rbind(label_1, label_2)
other_labels <- rbind(c(46:60),c(106:120))
pca_with_labels <- cbind(labels, pca$x)
colnames(pca_with_labels)[1] <- "Label"
pca_with_labels_df <- as.data.frame(pca_with_labels)

ggplot(pca_df, aes(x=PC1, y=PC2, col=Labels))+geom_point(size=1.4)+theme(aspect.ratio = 1)
ggplot(pca_df, aes(x=PC2, y=PC3, col=Labels))+geom_point(size=1.4)+theme(aspect.ratio = 1)
ggplot(pca_df, aes(x=PC1, y=PC3, col=Labels))+geom_point(size=1.4)+theme(aspect.ratio = 1)
```
```{r multidimensional-scaling}

d <- dist(rbind(vec_red[46:60,], vec_red[106:120,])) # euclidean distances between the rows
mds <- cmdscale(d,eig=TRUE, k=2) # k is the number of dim
label_1 <- matrix("GATA6", nrow=nimages, ncol=1)
label_2 <- matrix("HA", nrow=nimages, ncol=1)
Labels <- rbind(label_1, label_2)

# plot solution 
ggplot(as.data.frame(mds$points), aes(x=x, y=y, col=Labels))+geom_point(size=1.4)+theme(aspect.ratio = 1)
#points(cohort_distances_mds$points, col="black", pch=c(8,cohort_outline_pch), bty="n", ann=FALSE)
```

```{r 15 vs 25}
data_labels <- c(rep(1,15), rep(2,15), rep(1,15), rep(2,15))
pca <- prcomp(rbind(vectorized_avgPLs[31:60,], vectorized_avgPLs[91:120,]))
pchs <- c (rep("GATA6", 30), rep("HA", 30))
pca_df <- as.data.frame(pca$x)
label_3 <- matrix("15 ng/ml", nrow=nimages, ncol=1)
label_4 <- matrix("25 ng/ml", nrow=nimages, ncol=1)
Dox_concentration <- rbind(label_3, label_4, label_3, label_4)
pca_with_labels <- cbind(Dox_concentration, pchs, pca$x)
colnames(pca_with_labels)[1] <- "Label"
colnames(pca_with_labels)[2] <- "Symbol"
pca_with_labels_df <- as.data.frame(pca_with_labels)

ggplot(pca_df, aes(x=PC1, y=PC2, colour = Dox_concentration, shape = factor(pchs)))+geom_point(size=1.3)+theme(aspect.ratio = 1)+labs(
         colour = "Dox concentration",
         shape = "Group"
        )+scale_color_discrete(breaks=c("15 ng/ml", "25 ng/ml"))
ggplot(pca_df, aes(x=PC2, y=PC3, col=Dox_concentration))+geom_point(size=1.3)+theme(aspect.ratio = 1)
ggplot(pca_df, aes(x=PC1, y=PC3, col=Dox_concentration))+geom_point(size=1.3)+theme(aspect.ratio = 1)
```



```{r permutation test, eval=FALSE}
vectorized_PLs <- vec_gr[,1:(PL_length_gr*30)]
#vectorized_PLs <- vectorized_PLs[, colSums(abs(vectorized_PLs)) != 0]
#vectorized_PLs <- scale(vectorized_PLs)
#vectorized_PLs <- rbind(cbind(counts[[1]][,1],counts[[1]][,3]),cbind( counts[[2]][,1],counts[[2]][,3]))

#vectorized_PLs <- vec_red[, (PL_length_red*0+1):(PL_length_red*30)] #30 is PL_depth_cap
#vectorized_PLs <- vectorized_PLs[, colSums(abs(vectorized_PLs)) != 0]
#vectorized_PLs <- scale(vectorized_PLs)

nrepeats <- 10000
print("Permutation test results:")
p_value <- permutation.test(vectorized_PLs[(3*nimages*npatches+1):(3*nimages*npatches),],  vectorized_PLs[(3*nimages*npatches+1+4*nimages*npatches):(4*nimages*npatches+4*nimages*npatches),])
#p_value <- permutation.test(vectorized_PLs[(3*nimages*npatches+1):(4*nimages*npatches), ],   vectorized_PLs[(3*nimages*npatches+1+4*nimages*npatches):(4*nimages*npatches+4*nimages*npatches), ], num.repeats = nrepeats)
#p_value <- permutation.test(vectorized_PLs[(1*nsamples+1):(2*nsamples),], vectorized_PLs[(3*nsamples+1):(4*nsamples),])
print(sprintf("p-value %f:", p_value))
```

```{r SVM-one-vs-another-concentration}
cohort <- "Gata6"
if (cohort == "Gata6"){
  j <- 1 #if Gata6
} else {
  j <- 0 #if HA
}
print(cohort)
cost <-10
nrepeats <- 10
num_folds <- 10
n <- nsamples*nconcentrations #number of patches per cohort
ntest_data <- 2*nsamples/num_folds
data_labels <- matrix(c(rep(1,(nsamples)),rep(-1,(nsamples))))
vectorized_PLs <- cbind(vec_red[(1+n*(1-j)):(n+n*(1-j)), (PL_length_red*0+1):(PL_length_red*30)], vec_gr[(1+n*(1-j)):(n+n*(1-j)),(PL_length_gr*0+1):(PL_length_gr*30)], vec_pos[(1+n*(1-j)):(n+n*(1-j)), (PL_length_pos*0+1):(PL_length_pos*30)], vec_neg[(1+n*(1-j)):(n+n*(1-j)), (PL_length_neg*0+1):(PL_length_neg*30)])  #30 is PL_depth_cap
#vectorized_PLs <- vectorized_PLs[, colSums(abs(vectorized_PLs)) != 0]
#vectorized_PLs <- scale(vectorized_PLs)
#vectorized_PLs <- scale(counts[[1]])

vec <-list(rbind(vectorized_PLs[1:(nsamples),], vectorized_PLs[(nsamples+1):(2*nsamples),]), rbind(vectorized_PLs[1:(nsamples),], vectorized_PLs[(2*nsamples+1):(3*nsamples),]),
rbind(vectorized_PLs[1:(nsamples),], vectorized_PLs[(3*nsamples+1):(4*nsamples),]), rbind(vectorized_PLs[(nsamples+1):(2*nsamples),], vectorized_PLs[(2*nsamples+1):(3*nsamples),]), rbind(vectorized_PLs[(nsamples+1):(2*nsamples),], vectorized_PLs[(3*nsamples+1):(4*nsamples),]), rbind(vectorized_PLs[(2*nsamples+1):(3*nsamples),], vectorized_PLs[(3*nsamples+1):(4*nsamples),])) # length 6

accuracy <- list()
s <- list()
for (k in 1:length(vec)){
   s[[k]] <- list()
  for (j in 1:nrepeats){
    rand_perm <- sample(2*nsamples)
    vectorized_sample_PLs_permuted <- vec[[k]][rand_perm,]
    data_labels_permuted <- data_labels[rand_perm]
    svm_model <- list()
    predictions_list <- vector()
    predictions <- list()
    for (i in 1:num_folds){
       svm_model[[i]] <-  ksvm(vectorized_sample_PLs_permuted[-((ntest_data*(i-1)+1):(ntest_data*(i-1)+ntest_data)),],data_labels_permuted[-((ntest_data*(i-1)+1):(ntest_data*(i-1)+ntest_data))],type="C-svc",scaled = c(),kernel="vanilladot", C=cost)
       predictions[[i]] <- predict(svm_model[[i]],vectorized_sample_PLs_permuted[((ntest_data*(i-1) +   1)):(ntest_data*(i-1) +ntest_data),])
       predictions_list <- c(predictions_list, predictions[[i]])
    }
    #print(predictions_list)
  s[[k]][[j]] <- 0
  for (i in 1:(2*nsamples)){
    if (predictions_list[[i]] == data_labels_permuted[[i]]){
      s[[k]][[j]] <- s[[k]][[j]]+1
    }
   }
  }
  #print(k)
  #print(s[[k]])
  accuracy[[k]] <- sum(unlist(s[[k]]))/(nrepeats*2*nsamples)
  print(accuracy[[k]])
}
```


```{r confusion-matrix-multiclass-SVM}
cohort <- "Gata6"
if (cohort == "Gata6"){
  j <- 1 #if Gata6
} else {
  j <- 0 #if HA
}
print(cohort)
cost <- 10
num_folds <- 10
n <- nsamples*nconcentrations #number of patches per cohort
ntest_data <- n/num_folds
data_labels <- matrix(c(rep(0,nsamples), rep(5,nsamples), rep(15,nsamples), rep(25,nsamples)))
rand_perm <- a
#vectorized_PLs <- scale(counts[[1]])
vectorized_PLs <- cbind(vec_red[(1+n*(1-j)):(n+n*(1-j)), (PL_length_red*3+1):(PL_length_red*30)], vec_gr[(1+n*(1-j)):(n+n*(1-j)),(PL_length_gr*3+1):(PL_length_gr*30)],vec_pos[(1+n*(1-j)):(n+n*(1-j)),(PL_length_pos*3+1):(PL_length_pos*30)], vec_neg[(1+n*(1-j)):(n+n*(1-j)),(PL_length_neg*3+1):(PL_length_neg*30)])  #30 is PL_depth_cap
#vectorized_PLs <- vectorized_PLs[, colSums(abs(vectorized_PLs)) != 0]
#vectorized_PLs <- scale(vectorized_PLs)

vectorized_PLs_permuted <- vectorized_PLs[rand_perm,]
data_labels_permuted <- data_labels[rand_perm]
svm_model <- list()
predictions <- list()
for (i in 1:num_folds){
svm_model[[i]] <- ksvm(vectorized_PLs_permuted[-((ntest_data*(i-1) + 1):(ntest_data*(i-1)+ntest_data )),],data_labels_permuted[-((ntest_data*(i-1) + 1):(ntest_data*(i-1)+ntest_data ))],type="C-svc",scaled = FALSE,kernel="vanilladot")
predictions[[i]] <- predict(svm_model[[i]],vectorized_PLs_permuted[((ntest_data*(i-1) + 1):(ntest_data*(i-1)+ntest_data )),])
}
predictions <- unlist(predictions)
s <- 0
for (i in 1:n){
    if (predictions[[i]] == data_labels_permuted[[i]]){
      s <- s+1
    }
}
#for (i in 1:n){
#    if (predictions[[i]] != data.labels.permuted[[i]] & data.labels.permuted[[i]]==15 & predictions[[i]]==25){
 #     print(rand.perm[[i]])
#    }
#}
print(s/n)
table(unlist(predictions),data_labels_permuted)
```

```{r multiclass-SVM}
tic()
cohort <- "Gata6"
if (cohort == "Gata6"){
  j <- 1 #if Gata6
} else {
  j <- 0 #if HA
}
print(cohort)
cost <- 10
nrepeats <- 20
num_folds <- 10
n <- nsamples*nconcentrations #number of patches per cohort
ntest_data <- n/num_folds
data_labels <- matrix(c(rep(0,nsamples), rep(5,nsamples), rep(15,nsamples), rep(25,nsamples)))
#vectorized_PLs <- scale(counts[[2]])
vectorized_PLs <- cbind(vec_red[(1+n*(1-j)):(n+n*(1-j)), (PL_length_red*0+1):(PL_length_red*30)], vec_gr[(1+n*(1-j)):(n+n*(1-j)),(PL_length_gr*0+1):(PL_length_gr*30)],vec_pos[(1+n*(1-j)):(n+n*(1-j)),(PL_length_pos*0+1):(PL_length_pos*30)], vec_neg[(1+n*(1-j)):(n+n*(1-j)),(PL_length_neg*0+1):(PL_length_neg*30)]) #30 is PL_depth_cap
vectorized_PLs <- vectorized_PLs[, colSums(abs(vectorized_PLs)) != 0]
vectorized_PLs <- scale(vectorized_PLs)


accuracy <- list()
total_accuracy <- 0
for (k in 1:nrepeats){
  print(k)
  rand_perm <- sample(n)
  vectorized_PLs_permuted <- vectorized_PLs[rand_perm,]
  data_labels_permuted <- data_labels[rand_perm]
  svm_model <- list()
  predictions <- list()
  for (i in 1:num_folds){
    svm_model[[i]] <- ksvm(vectorized_PLs_permuted[-((ntest_data*(i-1) +    1):(ntest_data*(i-1)+ntest_data)),],data_labels_permuted[-((ntest_data*(i-1) + 1):(ntest_data*(i-1)+ntest_data))],type="C-svc",scaled = c(),kernel="vanilladot")
    predictions[[i]] <- predict(svm_model[[i]],vectorized_PLs_permuted[((ntest_data*(i-1) + 1):(ntest_data*(i-1)+ntest_data)),])
  }
  predictions <- unlist(predictions)
  s <- 0
  for (i in 1:n){
    if (predictions[[i]] == data_labels_permuted[[i]]){
      s <- s+1
    }
  }
#  for (i in 1:n){
 #   if (predictions[[i]] == data.labels.permuted[[i]] & data.labels.permuted[[i]]==0){
      #print(rand.perm[[i]])
  #  }
 # }
  accuracy[[k]] <- s/nrow(vectorized_PLs)
   print(accuracy[[k]])
  table(unlist(predictions),data_labels_permuted)
  total_accuracy <- total_accuracy+accuracy[[k]]
}

total_accuracy <- total_accuracy/nrepeats
print(total_accuracy)
toc()
```

```{r SVR}
tic()
cohort <- "HA"
if (cohort == "Gata6"){
  j <- 1 #if Gata6
} else {
  j <- 0 #if HA
}
print(cohort)
cost <- 10
nrepeats <- 20
num_folds <- 10
n <- nsamples*nconcentrations #number of patches per cohort
ntest_data <- n/num_folds
#vectorized_PLs <- scale(counts[[2]])
vectorized_PLs <- cbind(vec_red[(1+n*(1-j)):(n+n*(1-j)), (PL_length_red*0+1):(PL_length_red*30)], vec_gr[(1+n*(1-j)):(n+n*(1-j)),(PL_length_gr*0+1):(PL_length_gr*30)],vec_pos[(1+n*(1-j)):(n+n*(1-j)),(PL_length_pos*0+1):(PL_length_pos*30)], vec_neg[(1+n*(1-j)):(n+n*(1-j)),(PL_length_neg*0+1):(PL_length_neg*30)]) #30 is PL_depth_cap
vectorized_PLs <- vectorized_PLs[, colSums(abs(vectorized_PLs)) != 0]
vectorized_PLs <- scale(vectorized_PLs)

data_labels <- c(rep(0,nsamples),rep(5,nsamples),rep(15,nsamples),rep(25,nsamples))
predictions_list <- list()
for (k in 1:nrepeats){
  print(k)
  rand_perm <- sample(n)
  perm_inv <- invPerm(rand_perm)
  vectorized_PLs_permuted <- vectorized_PLs[rand_perm,]
  data_labels_permuted <- data_labels[rand_perm]
  svr_model <- list()
  predictions_svr <- list()
  for (i in 1:num_folds){
    svr_model[[i]] <- ksvm(vectorized_PLs_permuted[-((ntest_data*(i-1) + 1):(ntest_data*(i-1)+ntest_data)),],data_labels_permuted[-((ntest_data*(i-1) + 1):(ntest_data*(i-1)+ntest_data))],scaled  = FALSE ,kernel="vanilladot",C = cost,epsilon = 0.01)
    predictions_svr[[i]] <- predict(svr_model[[i]],vectorized_PLs_permuted[((ntest_data*(i-1) + 1):(ntest_data*(i-1)+ntest_data)),])
  }
  predictions_list[[k]] <- unlist(predictions_svr)[perm_inv]
}

prediction = NULL
for (k in 1:nrepeats){
  prediction = rbind(prediction,predictions_list[[k]])
}
prediction = colSums(prediction)/nrepeats
toc()
```

```{r SVR-patches-ggplot}
concentration <- c(rep("0",nsamples),rep("5",nsamples),rep("15",nsamples),rep("25",nsamples))
value <- c( unlist(prediction) )
data <- data.frame(concentration, value)
#new_data <- data
#new_data$concentration <- factor(data$concentration , levels=c("0", "5", "15", "25"))


ggplot(data, aes(x=concentration, y=value, fill=concentration)) +scale_x_discrete(limits=c("0", "5", "15", "25"))+
    geom_boxplot(alpha=0.4)  +
    theme(
      plot.title = element_text(size=11), aspect.ratio=1)+
    xlab("")+ylab("predicted Dox concentration")+labs(title="RFP = HA")+theme(plot.title=element_text(hjust=0.5))+coord_cartesian(ylim=c(-25,45))+scale_y_continuous(breaks = c(-5, 0, 5, 10,15,20,25,30))+scale_fill_discrete(breaks=c('0', '5', '15', '25'))
```

```{r plot-SVR-images}
prediction_images <- vector()
for (i in 1:(nimages*nconcentrations)){
  prediction_images[i] <- mean(sort(prediction[((i-1)*npatches+1):(i*npatches)]))
}
data_labels <- c(rep(0,nimages),rep(5,nimages),rep(15,nimages),rep(25,nimages))
c <- c("aquamarine3", "yellow","lightskyblue2", "orange")
symbols <- c(21:24)
plot(0, col="white", bty="o", xlim=c(1,nimages*nconcentrations), ylim=c(min(prediction_images),max(prediction_images)), ylab="estimated dox concentration", xlab="images")
grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dotted",
     lwd = par("lwd"), equilogs = TRUE)
for (i in 1:nconcentrations){
  low_i <- (i-1)*nimages+1
  high_i <- i*nimages
  lines(cbind(low_i:high_i,data_labels[low_i:high_i]))
  points(cbind(low_i:high_i,prediction_images[low_i:high_i]), pch=symbols[[i]], bg=c[i])
}
legend("topleft", cex=0.8, inset=0.01, legend=c("0", "5", "15", "25"),
       pt.bg=c, pch=symbols, title=" Ground Truth ")

data <- data.frame(labels=c(rep(0,nimages),rep(5,nimages),rep(15,nimages),rep(25,nimages)), values =c(prediction_images[1:nimages], prediction_images[(nimages+1):(2*nimages)], prediction_images[(2*nimages+1):(3*nimages)], prediction_images[(3*nimages+1):(4*nimages)]))



boxplot(data$values ~ data$labels, col=c, xlab="concentration", ylab="predicted Dox concentration", ylim=c(-5,30))
grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dotted",
     lwd = par("lwd"), equilogs = TRUE)
stripchart(data$values ~ data$labels, vertical=TRUE, method="jitter", pch=19, col='black', add=TRUE, jitter=0.3, cex=0.9)

```

```{r plot-SVR-images-ggplot}
prediction_images <- vector()
for (i in 1:(nimages*nconcentrations)){
  prediction_images[i] <- mean(sort(prediction[((i-1)*npatches+1):(i*npatches)]))
}

concentration <- c(rep("0",nimages),rep("5",nimages),rep("15",nimages),rep("25",nimages))
value <- c( unlist(prediction_images) )
data <- data.frame(concentration, value)
#new_data <- data
#new_data$concentration <- factor(data$concentration , levels=c("0", "5", "15", "25"))


SVR_H_mean <- ggplot(data, aes(x=concentration, y=value, fill=concentration)) +scale_x_discrete(limits=c("0", "5", "15", "25"))+
    geom_boxplot(alpha=0.4)  +
    geom_jitter(color="black", size=0.7, alpha=0.9)+
    theme(
      plot.title = element_text(size=11), aspect.ratio=1)+
    xlab("")+ylab("predicted Dox concentration")+coord_cartesian(ylim=c(0,28))+scale_y_continuous(breaks = c(-5, 0, 5, 10,15,20,25,30))+scale_fill_discrete(breaks=c('0', '5', '15', '25'))+guides(fill=guide_legend(title="Dox concentration"))
```

```{r ggarange-plots}
################for knn computations 
#SVR_G_mean 
#SVR_G_med
#SVR_H_mean 
#SVR_H_med
###############
#SVR_G_med
#SVR_G_mean
#SVR_G_mean6_11
#SVR_G_med_sc0_30
#SVR_G_mean_sc0_30
#SVR_G_mean_6_11_sc0_30
ggarrange(SVR_G_med, SVR_H_med, nrow=1,common.legend = TRUE, legend = "bottom")
ggarrange(SVR_G_mean, SVR_H_mean, nrow=1,common.legend = TRUE, legend = "bottom")
#ggarrange(SVR_G_med_sc0_30, SVR_H_med_sc0_30, nrow=1,common.legend = TRUE, legend = "right")
#ggarrange(SVR_G_med, SVR_H_med, nrow=1,common.legend = TRUE, legend = "bottom")

```

